### ISSUE TITLE
1.0.0 (and missing LICENSE file)

### ISSUE THREAD

**Issue by dcousens** [Rich-Harris/estree-walker#6]
Any reason to hold off from a `1.0.0` release?  Is this package considered stable?

Also, you unambiguously specify this is under the MIT LICENSE,  but,  you don't provide the LICENSE yourself in either the npm publication or this repository.

From the [MIT LICENSE](https://en.wikipedia.org/wiki/MIT_License#License_terms):
> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

Where (and what is the contents of) the copyright notice? etc

**Comment by Rich-Harris** [comment]
Belated thanks — added a LICENSE file (and 1.0.0 was released long ago)
